// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mix-analyzer-variants/EditorialBrief.tsx": () => import("../components/mockups/mix-analyzer-variants/EditorialBrief.tsx"),
  "./components/mockups/mix-analyzer-variants/RadarShape.tsx": () => import("../components/mockups/mix-analyzer-variants/RadarShape.tsx"),
  "./components/mockups/mix-analyzer-variants/SequentialReveal.tsx": () => import("../components/mockups/mix-analyzer-variants/SequentialReveal.tsx")
};
